CREATE DATABASE IF NOT EXISTS e_commerce_db 
DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_

USE e_commerce_db;
--创建角色
-- ROLE ROOT
CREATE ROLE BOSS;
CREATE ROLE CARGO_MANAGER;
CREATE ROLE COMMODITY_TRADER;
CREATE ROLE AUDITOR;
CREATE ROLE CUSTOMER;

--为各角色授权
GRANT ALL PRIVILEGES 
ON `E_COMMERCE_DB`.`PRODUCTS`,`E_COMMERCE_DB`.`INVENTORY`,`E_COMMERCE_DB`.`TRANSACTIONS`,`E_COMMERCE_DB`.`TRANSACTION_DETAILS`,`E_COMMERCE_DB`.`SUBSIDY_POLICIES`,`DISCOUNT_POLICIES`
TO BOSS
WITH ADMIN OPTION

GRANT ALL PRIVILEGES
ON `E_COMMERCE_DB`.`PRODUCTS`,`E_COMMERCE_DB`.`INVENTORY`
TO CARGO_MANAGER

GRANT ALL PRIVILEGES
ON `E_COMMERCE_DB`.`PRODUCTS`,`E_COMMERCE_DB`.`TRANSACTIONS`,`E_COMMERCE_DB`.`TRANSACTION_DETAILS`,`E_COMMERCE_DB`.`SUBSIDY_POLICIES`,`E_COMMERCE_DB`.`DISCOUNT_POLICIES`,`E_COMMERCE_DB`.`USERS`
TO COMMODITY_TRADER

GRANT ALL PRIVILEGES
ON `E_COMMERCE_DB`.`AUDIT_LOGS`
TO AUDITOR

GRANT SELECT 
ON `E_COMMERCE_DB`.`DISCOUNT_POLICIES`,`E_COMMERCE_DB`.`PRODUCTS`
TO CUSTOMER




