USE E_COMMERCE_DB
--创建示例用户
CREATE USER 'BOSS1'@'%' IDENTIFIED BY '123';
CREATE USER 'BOSS2'@'%' IDENTIFIED BY '123';
CREATE USER 'CARGO'@'%' IDENTIFIED BY '123';
CREATE USER 'TRADER'@'%' IDENTIFIED BY '123';
CREATE USER 'CUSTOMER1'@'%' IDENTIFIED BY '123';

--为用户授权
GRANT BOSS
TO BOSS1

--登陆用户BOSS1,并将权限授予BOSS2
--用图形化工具登录
GRANT BOSS
TO BOSS2

GRANT CARGO_MANAGER
TO CARGO

GRANT COMMODITY_TRADER
TO TRADER

GRANT CUSTOMER
TO CUSTOMER1

--查询权限
SHOW GRANTS FOR 'BOSS1'@'%';
SHOW GRANTS FOR 'BOSS2'@'%';
SHOW GRANTS FOR 'CARGO'@'%';
SHOW GRANTS FOR 'TRADER'@'%';
SHOW GRANTS FOR 'CUSTOMER1'@'%';




